// ---------------------------------------------------------------------------
// Schema version lifecycle — the declaration registry.
//
// GENERATED from the scanner inventory and the curated persistence/disposition
// tables in the schema-version-lifecycle campaign session. Every discovered
// `nightwatch.<name>.v<n>` identifier under src/** has exactly one entry here.
//
// `persisted` is a CURATED classification, not a heuristic: a family is marked
// persisted only when a named store module writes it. Everything absent from the
// persistence list is declared IN_MEMORY and carries no owner-state cost when its
// version is bumped. `versions` records the role of every DISCOVERED version:
// CURRENT (written by this build), READ_COMPATIBLE (old bytes a current reader
// still accepts), MIGRATED (old bytes readable only through the registered
// migration), ORPHANED (deliberately unreadable; requires a DECISIONS reference),
// SYNTHETIC_PROBE (a deliberate unknown-version literal in an adversarial
// fixture, never owner data), or IN_MEMORY_HISTORICAL (an old in-process shape).
//
// A persisted non-current version MUST carry a disposition below. ORPHAN is
// never a default: D-126 records that it requires an explicit owner decision.
// ---------------------------------------------------------------------------

import type { SchemaFamilyDeclaration } from './types';

export const SCHEMA_FAMILIES: readonly SchemaFamilyDeclaration[] = [
  { family: 'nightwatch.dependency-currency', persisted: true, store: 'REPOSITORY_CORPUS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: 'repository configuration record; the advisory lane stays unavailable until a registry query is authorized' },
  { family: 'nightwatch.environment-surface', persisted: true, store: 'REPOSITORY_CORPUS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: 'repository configuration record declaring every environment variable' },
  { family: 'nightwatch.reasoner-identity', persisted: true, store: 'AGENT_RECORDS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: 'reasoner executable identity recorded in local campaign run evidence' },
  { family: 'nightwatch.agent-budget', persisted: true, store: 'AGENT_RECORDS', currentVersion: 2, versions: { 1: 'MIGRATED', 2: 'CURRENT' }, dispositions: [{ fromVersion: 1, toVersion: 2, kind: 'MIGRATE', migrationId: 'agent-budget-v1-to-v2', reason: "v1 checkpoints carry one mixed outputBytes total; the documented v1->v2 migration moves the mixed total into toolPayloadBytes and rebuilds the byte ledger, so a v1 checkpoint resumes under v2 arithmetic." }], note: "" },
  { family: 'nightwatch.agent-byte-ledger', persisted: true, store: 'AGENT_RECORDS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.agent-checkpoint', persisted: true, store: 'AGENT_RECORDS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.agent-protocol', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.agent-runtime-state', persisted: true, store: 'AGENT_RECORDS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.agent-tool-protocol', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.agent-tool-runtime', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.ai-bug-draft-output.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.ai-bug-draft.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 2, versions: { 1: 'READ_COMPATIBLE', 2: 'CURRENT' }, dispositions: [{ fromVersion: 1, toVersion: 2, kind: 'READ_COMPATIBLE', fixtureId: 'ai-bug-draft-v1', reason: "the v2 reader dispatches validateLegacyAiBugDraft for v1 records; Phase 7B drafts stay readable." }], note: "" },
  { family: 'nightwatch.ai-human-review.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 2, versions: { 1: 'READ_COMPATIBLE', 2: 'CURRENT' }, dispositions: [{ fromVersion: 1, toVersion: 2, kind: 'READ_COMPATIBLE', fixtureId: 'ai-human-review-v1', reason: "the v2 reader dispatches validateLegacyAiHumanReviewRecord for v1 records." }], note: "" },
  { family: 'nightwatch.ai-oracle-suggestion-output.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.ai-oracle-suggestion.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 2, versions: { 1: 'READ_COMPATIBLE', 2: 'CURRENT' }, dispositions: [{ fromVersion: 1, toVersion: 2, kind: 'READ_COMPATIBLE', fixtureId: 'ai-oracle-suggestion-v1', reason: "the v2 reader dispatches validateLegacyAiOracleSuggestion for v1 records." }], note: "" },
  { family: 'nightwatch.ai-provider-adapter.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.ai-ready-evidence.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.ai-review-budget.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.ai-review-input.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.ai-review-prompt.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.alphaus-finding-handoff', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.anomaly-cluster.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.api-catalog.phase5', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.api-generator.phase5', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.api-oracle.phase5', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.artifact-validation.private', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.atlas-query', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.auth-capability-preflight', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.auth-capability-record', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.auth-capability-report', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.auth-capture-lifetime-measurement', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.autonomous-finding-dossier', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.autonomous-finding-handoff-projection', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.baseline.phase3', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.bug-atlas-fixture-corpus', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.bug-atlas-miner', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.bug-atlas-record', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.bug-atlas-store', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.bug-dossier.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 2, versions: { 1: 'READ_COMPATIBLE', 2: 'CURRENT', 9: 'SYNTHETIC_PROBE' }, dispositions: [{ fromVersion: 1, toVersion: 2, kind: 'READ_COMPATIBLE', fixtureId: 'bug-dossier-v1', reason: "validateDossierArtifact dispatches v1 and v2; both dossier shapes remain readable." }], note: "unsupported-version probe v9 proven by the Phase 13 shadow corpus (src/core/phase13/shadow.ts)" },
  { family: 'nightwatch.c12-local-rehearsal-config', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.c12-local-rehearsal-receipt', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.c12-readiness', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.cache-key-contracts', persisted: true, store: 'REPOSITORY_CORPUS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "owner-declared cache-key contract registry (config/cache-key-contracts.v1.json); the only pair authority" },
  { family: 'nightwatch.cache-key-report', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "sanitized Wave 1 C4 Phase 1a report under artifacts/cache-key-contract/; report only, never a finding" },
  { family: 'nightwatch.cache-key-shape-extraction', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "closed key-shape grammar/extraction identity carried inside cks:/ckp: digests" },
  { family: 'nightwatch.record-identity-contracts', persisted: true, store: 'REPOSITORY_CORPUS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "owner-declared record-identity contract registry (config/record-identity-contracts.v1.json); the only identity-family authority" },
  { family: 'nightwatch.record-identity-report', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "sanitized Wave 2 C5 report under artifacts/record-identity/; synthetic reproductions only, productionStateClaim NONE" },
  { family: 'nightwatch.record-identity-extraction', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "bounded Go record-identity extraction identity carried inside rks:/rst:/rid: digests" },
  { family: 'nightwatch.test-oracle-quality', persisted: true, store: 'REPOSITORY_CORPUS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "owner-declared test-oracle quality targets and intentional-skip declarations (config/test-oracle-quality.v1.json)" },
  { family: 'nightwatch.test-assurance-report', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "sanitized Wave 2 C8 assurance-gap report under artifacts/test-oracle-quality/; never a finding" },
  { family: 'nightwatch.silent-zero-output-contracts', persisted: true, store: 'REPOSITORY_CORPUS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "owner-declared silent zero-output handler/input contracts (config/silent-zero-output-contracts.v1.json)" },
  { family: 'nightwatch.silent-zero-output-report', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "sanitized Wave 2 C1 static-precursor report under artifacts/silent-zero-output/; runtimeFailureClaim NONE" },
  { family: 'nightwatch.call-scoped-source-read', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.campaign-budget.private', persisted: true, store: 'CAMPAIGN_CHECKPOINTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.campaign-cache', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.campaign-candidate-record.private', persisted: true, store: 'CAMPAIGN_CHECKPOINTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.campaign-checkpoint.private', persisted: true, store: 'CAMPAIGN_CHECKPOINTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.campaign-coverage', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.campaign-diagnostic', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.campaign-impact-report', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.campaign-manifest.private', persisted: true, store: 'CAMPAIGN_CHECKPOINTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.campaign-morning-brief.private', persisted: true, store: 'CAMPAIGN_CHECKPOINTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.campaign-plan', persisted: false, store: 'IN_MEMORY', currentVersion: 2, versions: { 2: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.campaign-plan-manifest', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.campaign-portfolio-runtime-binding', persisted: true, store: 'CAMPAIGN_CHECKPOINTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.campaign-portfolio.private', persisted: true, store: 'CAMPAIGN_CHECKPOINTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.campaign-resume-terminal', persisted: true, store: 'CAMPAIGN_CHECKPOINTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "terminal resume marker written beside a refused campaign checkpoint" },
  { family: 'nightwatch.campaign-runtime-profile', persisted: true, store: 'CAMPAIGN_CHECKPOINTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.campaign-semantic-evidence', persisted: true, store: 'CAMPAIGN_CHECKPOINTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.campaign-strategy-state', persisted: true, store: 'CAMPAIGN_CHECKPOINTS', currentVersion: 2, versions: { 1: 'READ_COMPATIBLE', 2: 'CURRENT' }, dispositions: [{ fromVersion: 1, toVersion: 2, kind: 'READ_COMPATIBLE', fixtureId: 'campaign-strategy-state-v1', reason: "parseCampaignStrategyState reads v1 with an empty unsupportedTargets refusal record and re-stamps v2." }], note: "" },
  { family: 'nightwatch.campaign-yield', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.campaign.private', persisted: true, store: 'CAMPAIGN_CHECKPOINTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.candidate-invalidation', persisted: false, store: 'IN_MEMORY', currentVersion: 2, versions: { 2: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.candidate-lifecycle.private', persisted: true, store: 'CAMPAIGN_CHECKPOINTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.canonical-digest', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.census-figure-ledger', persisted: true, store: 'AGENT_RECORDS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.change-intelligence.phase3', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.confidence', persisted: false, store: 'IN_MEMORY', currentVersion: 2, versions: { 2: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.contract-coverage-report', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.contract-discovery', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.contract-lifecycle-model', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.contract-lifecycle-registry', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.contract-lifecycle-resolution-view', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.contract-migration-map', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.contract-result-vocabulary', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.contract-schema-validation', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.control-center-campaign-authority', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.control-center-findings-authority', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.control-center-snapshot-coordinator', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.control-center-source-authority', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.control-center.error', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.control-center.review-decision', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.cross-layer-comparator.phase6', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.cross-layer-lineage.phase6', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.current-failure-evidence', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.data-adapter.phase6', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.data-evidence.phase6', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.data-normalizer.phase6', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.data-oracle-catalog.phase6', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.dependency-map', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.deployment-binding', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.deployment-manifest-reader', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.derived-endpoint-semantics', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.dev-campaign-handoff', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.dev-preflight-receipt', persisted: false, store: 'IN_MEMORY', currentVersion: 2, versions: { 2: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.dev-semantic-acceptance-dry-run', persisted: false, store: 'IN_MEMORY', currentVersion: 2, versions: { 1: 'IN_MEMORY_HISTORICAL', 2: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.dev-semantic-acceptance-manifest', persisted: true, store: 'AGENT_RECORDS', currentVersion: 2, versions: { 1: 'READ_COMPATIBLE', 2: 'CURRENT' }, dispositions: [{ fromVersion: 1, toVersion: 2, kind: 'READ_COMPATIBLE', fixtureId: 'phase22-manifest-v1', reason: "the current build retains validatePhase22Manifest and the Phase 23 historical derivation bridge reads a v1 manifest." }], note: "" },
  { family: 'nightwatch.efficacy-corpus', persisted: false, store: 'IN_MEMORY', currentVersion: 2, versions: { 2: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.efficacy-corpus-report', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.efficacy-metrics', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.evidence-retention', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.evidence.phase2c', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.expectation-derivation', persisted: false, store: 'IN_MEMORY', currentVersion: null, versions: { 9: 'SYNTHETIC_PROBE' }, dispositions: [], note: "unsupported-version probe v9 proven by the Phase 13 shadow corpus (src/core/phase13/shadow.ts)" },
  { family: 'nightwatch.expected-information-gain', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.exploration-model', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.exploration-model.phase4', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.exploration-state.phase4', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.exploration-transition.phase4', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.exploration.phase4', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.failure-minimization.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.finding-cluster', persisted: false, store: 'IN_MEMORY', currentVersion: 2, versions: { 2: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.finding-intel', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.finding-review-lifecycle', persisted: true, store: 'REVIEW_STORE', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.finding-review-receipt', persisted: true, store: 'REVIEW_STORE', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.frontend-consumer', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.frontend-consumer-graph', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.go-grpc-registration', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.grpc-service-topology', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.historical-benchmark-case', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.historical-bug-atlas', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.historical-evidence', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.historical-reader-table', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.historical-reproduction', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.historical-source', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.historical-system-atlas', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.historical-system-map', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.investigation-memory', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.journey-contract', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.journey-oracle', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.journey.phase2c', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.l6-af-unix-control', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.l6-runtime-capability', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.live-state', persisted: true, store: 'AGENT_RECORDS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.local-cli-campaign', persisted: true, store: 'AGENT_RECORDS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.local-cli-campaign-progress', persisted: true, store: 'AGENT_RECORDS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.local-investigation-context', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.local-investigation-history', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.local-investigation-session', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.local-model-canary-input.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.local-model-canary-result.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.local-readiness', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.local-reproduction-receipt', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.local-triage-manifest', persisted: false, store: 'IN_MEMORY', currentVersion: 3, versions: { 3: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.mechanical-analyzer-evidence', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.mechanical-contract-analyzer', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.metamorphic-relation', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.mined-test-replay', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.minimality-evidence.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.minimization', persisted: false, store: 'IN_MEMORY', currentVersion: 2, versions: { 2: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.minimization-budget.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.morning-brief.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.nondeterminism', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.oops-adapter.phase5', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.oops-profile.phase5', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.oops-sandbox-status', persisted: false, store: 'IN_MEMORY', currentVersion: 2, versions: { 2: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.open-work-report', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.oracle.phase2c', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.orchestrator.private', persisted: true, store: 'CAMPAIGN_CHECKPOINTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.overnight-summary.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.owner-dossier', persisted: false, store: 'IN_MEMORY', currentVersion: 6, versions: { 3: 'IN_MEMORY_HISTORICAL', 4: 'IN_MEMORY_HISTORICAL', 5: 'IN_MEMORY_HISTORICAL', 6: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.owner-local-current-source-proof', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.owner-local-current-source-reproduction', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.owner-local-investigation-context', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.owner-local-reproduction-attempt', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.owner-local-reproduction-observation', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.owner-local-reproduction-target', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.owner-scope-policy', persisted: false, store: 'IN_MEMORY', currentVersion: 2, versions: { 2: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.owner-scope.policy', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.p1-kill-switch', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.p1-observation-scope', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.p1-observe-grant', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.p1-safe-observation-receipt', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.p1-scope-config', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.phase13.synthetic-seeds', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.phase22-candidate-inventory', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.phase22-real-differential-eligibility', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.phase22-real-eligibility', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.phase22-source-freshness', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.phase24-campaign-bridge', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.phase24-candidate-portfolio', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.phase24-ci-observability', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.phase24-cross-candidate-evaluation', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.phase24-minimization', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.phase24-no-contact-rehearsal-receipt', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.phase24-owner-review-dossier', persisted: false, store: 'IN_MEMORY', currentVersion: 2, versions: { 2: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.phase24-portfolio-selection', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.phase24-readiness-diagnostics', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.phase24-replay', persisted: false, store: 'IN_MEMORY', currentVersion: 4, versions: { 4: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.phase24-safe-cross-candidate-observation', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.phase24-safe-semantic-observation', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.phase24-semantic-evaluation', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.phase24-source-snapshot-analysis', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.phase24-synthetic-campaign', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.phase9-fixture-matrix', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.phase9b-pass-summary', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.php-effect-closure', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.php-effect-vocabulary', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.php-route-pipeline', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.planner', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.portfolio-allocation', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.portfolio-budget-mapping', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.portfolio-change-impact', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.portfolio-priority', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.portfolio-real-universe', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.portfolio-replan', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.portfolio-runtime-plan-document', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.portfolio-simulator', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.portfolio-yield-accounting', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.affected-tests', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "F-PERF-4 deterministic affected-test selection envelope; data-only" },
  { family: 'nightwatch.playwright-timings', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "F-PERF-1 ephemeral runner telemetry written under the ignored test-results/timings/ directory and regenerated per invocation; no owner-state migration obligation" },
  { family: 'nightwatch.pre-dev-authority-receipt', persisted: false, store: 'IN_MEMORY', currentVersion: 3, versions: { 3: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.pre-fix-source', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.private-artifact-policy', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.private-artifact.policy', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.private-screening', persisted: false, store: 'IN_MEMORY', currentVersion: 2, versions: { 2: 'CURRENT' }, dispositions: [], note: "NW-AUD-019 structural primary; v1 retired with the quote-blind labeled-value regex." },
  { family: 'nightwatch.process-network-containment', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.prod-observe-config', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.prod-observe-grant', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.product-adapter', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.production-admission-chain', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.production-artifact-policy', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.production-breakers', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.production-browser-profile', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.production-budget', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.production-evidence', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.production-kill-switch', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.production-loadability', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.production-persistence-audit', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.production-privacy-policy', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.production-projection', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.production-qualification-receipt', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.production-read-capability', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.production-read-guard', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.production-run-gate', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.production-track', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.production-vocabulary-authority', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.project-snapshot', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.project-state', persisted: true, store: 'AGENT_RECORDS', currentVersion: 2, versions: { 2: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.promotion-result.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.proto-declarations', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.proto-lexer', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.proto-openapi-corroboration', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.proto-service-index', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.proto-source-extractor', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.proven-key-vocabulary', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.proven-route-vocabulary', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.proxy-containment', persisted: false, store: 'IN_MEMORY', currentVersion: 2, versions: { 2: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.proxy-port-lease', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.proxy-summary', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 2, versions: { 2: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.quality-gate', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.quality-gate-receipt', persisted: true, store: 'GATE_RECEIPTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.query-validator.phase6', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.read-only-proof', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.readonly-query-plan.phase6', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.real-observation-privacy', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.real-semantic-calibration', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.real-semantic-replay', persisted: false, store: 'IN_MEMORY', currentVersion: 4, versions: { 4: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.real-source-collection-expectation-derivation', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.real-source-coverage-inventory', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.real-source-eligibility-census', persisted: false, store: 'IN_MEMORY', currentVersion: 3, versions: { 3: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.real-source-expectation-derivation', persisted: false, store: 'IN_MEMORY', currentVersion: 2, versions: { 1: 'IN_MEMORY_HISTORICAL', 2: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.real-source-expectation-recipe', persisted: true, store: 'REPOSITORY_CORPUS', currentVersion: 2, versions: { 1: 'READ_COMPATIBLE', 2: 'CURRENT' }, dispositions: [{ fromVersion: 1, toVersion: 2, kind: 'READ_COMPATIBLE', fixtureId: 'real-source-recipe-v1', reason: "validateRealSourceRecipe accepts v1 and v2; the retired v1 recipes stay byte-meaning-stable." }], note: "" },
  { family: 'nightwatch.real-source-gap-taxonomy', persisted: false, store: 'IN_MEMORY', currentVersion: 3, versions: { 3: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.real-source-gap-taxonomy-change', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.real-source-readonly-candidate-census', persisted: false, store: 'IN_MEMORY', currentVersion: 2, versions: { 2: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.real-source-response-analyzers', persisted: false, store: 'IN_MEMORY', currentVersion: 4, versions: { 4: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.real-source-response-flow', persisted: false, store: 'IN_MEMORY', currentVersion: 2, versions: { 2: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.real-source-review-queue', persisted: false, store: 'IN_MEMORY', currentVersion: 3, versions: { 3: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.real-source-scan-config', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.real-source-scan-extractor', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.real-source-snapshot-inventory', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.real-source-surface-cache', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.real-source-surface-change-report', persisted: false, store: 'IN_MEMORY', currentVersion: 2, versions: { 2: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.real-source-surface-descriptor', persisted: false, store: 'IN_MEMORY', currentVersion: 5, versions: { 3: 'IN_MEMORY_HISTORICAL', 5: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.real-source-surface-performance', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.reasoner-driver', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.reasoner-turn-request', persisted: false, store: 'IN_MEMORY', currentVersion: 2, versions: { 2: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.reasoner-turn-response', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.relational-semantic-contract', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.release-certification', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.release-freshness-report', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "sanitized Wave 1 C6 report under artifacts/release-freshness/; ref containment only, DEPLOYMENT_CLAIM: NONE" },
  { family: 'nightwatch.release-refs', persisted: true, store: 'REPOSITORY_CORPUS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "owner-declared release-ref inventory (config/release-refs.v1.json); the only pair/ref authority" },
  { family: 'nightwatch.replay-fidelity', persisted: false, store: 'IN_MEMORY', currentVersion: 4, versions: { 4: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.repository-discovery', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.reproduction-capability-census', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.reproduction-surface-map', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.provider-failure-classification', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "W13 R-03 provider failure taxonomy evidence; classes, signals, and counters only" },
  { family: 'nightwatch.provider-resilience-policy', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "W13 Phase B predeclared failover policy and fingerprint; data-only, no authority" },
  { family: 'nightwatch.request-parameter-provenance', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.review-store', persisted: true, store: 'REVIEW_STORE', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.ripple-dependency-map', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.runtime-budget-envelope', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "derived copy of the engine budget policy; never a second authority (D-139)" },
  { family: 'nightwatch.safe-actions.phase4', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.scenario-generator.phase5', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.schema-bump-impact', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "bump-time impact report; printed, never stored as authority" },
  { family: 'nightwatch.schema-export', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "sanitized owner export written only to an owner-chosen path outside the repository" },
  { family: 'nightwatch.schema-version-lifecycle', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "judgement envelope emitted by the lifecycle check itself" },
  { family: 'nightwatch.selector.phase3', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.selfdev-adopted-case', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.selfdev-adopted-case-catalog.generated', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.selfdev-adoption-plan.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.selfdev-adoption-sandbox-result.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.selfdev-adoption-strategy', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.selfdev-candidate.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.selfdev-canonical-apply-receipt.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.selfdev-canonical-promotion-approval.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.selfdev-canonical-promotion-verification.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.selfdev-canonical-promotion.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.selfdev-contract.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 2, versions: { 2: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.selfdev-evaluation.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 2, versions: { 1: 'READ_COMPATIBLE', 2: 'CURRENT' }, dispositions: [{ fromVersion: 1, toVersion: 2, kind: 'READ_COMPATIBLE', fixtureId: 'selfdev-evaluation-v1', reason: "legacy session artifacts carry v1 evaluations and validateLegacySessionArtifact reads them." }], note: "" },
  { family: 'nightwatch.selfdev-provenance.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.selfdev-replay-algorithm', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.selfdev-replay-descriptor.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.selfdev-result-state-machine', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.selfdev-session.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 2, versions: { 1: 'READ_COMPATIBLE', 2: 'CURRENT' }, dispositions: [{ fromVersion: 1, toVersion: 2, kind: 'READ_COMPATIBLE', fixtureId: 'selfdev-session-v1', reason: "legacy v1 session artifacts remain readable through validateLegacySessionArtifact; v2 is written for new sessions." }], note: "" },
  { family: 'nightwatch.selfdev-source-bundle.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.selfdev-synthetic-portfolio', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.selfdev-synthetic-selection', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.selfdev-trust-assessment.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.semantic-acceptance-class', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.semantic-campaign-bundle.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT', 9: 'SYNTHETIC_PROBE' }, dispositions: [], note: "unsupported-version probe v9 proven by the Phase 13 shadow corpus (src/core/phase13/shadow.ts)" },
  { family: 'nightwatch.semantic-campaign-integration', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.semantic-cluster', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.semantic-compatibility', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.semantic-contract-graph', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.semantic-contract-identity', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.semantic-coverage-cache', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.semantic-coverage-quality', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.semantic-coverage.private', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.semantic-differential', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.semantic-differential-alignment', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.semantic-differential-pair-discovery', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.semantic-dossier-evidence', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.semantic-evaluation-receipt', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 2, versions: { 1: 'READ_COMPATIBLE', 2: 'CURRENT', 9: 'SYNTHETIC_PROBE' }, dispositions: [{ fromVersion: 1, toVersion: 2, kind: 'READ_COMPATIBLE', fixtureId: 'semantic-receipt-v1', reason: "validateSemanticEvaluationReceipt accepts v1 and v2; v1 differs only in the version string." }], note: "unsupported-version probe v9 proven by the Phase 13 shadow corpus (src/core/phase13/shadow.ts)" },
  { family: 'nightwatch.semantic-expectation', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.semantic-gap-closure', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.semantic-lifecycle', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.semantic-membership-projection', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.semantic-observation-features', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.semantic-operation-count', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.semantic-oracle-finding', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.semantic-projection', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.semantic-replay-fidelity.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 3, versions: { 3: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.semantic-result-vocabulary', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.semantic-scenario-binding', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.semantic-source-analyzers', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.semantic-triage-evidence', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT', 9: 'SYNTHETIC_PROBE' }, dispositions: [], note: "unsupported-version probe v9 proven by the Phase 13 shadow corpus (src/core/phase13/shadow.ts)" },
  { family: 'nightwatch.simulated-investigator', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.source-contract-movement', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.source-contract-resolution', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.source-evidence-digest', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.source-evidence-provenance', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.source-inventory-completeness', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.source-join', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.source-operation-projection-completeness', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.source-population-completeness', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.spec-derived-expectation', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.spec-scenario-inventory', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.status-word-ledger', persisted: true, store: 'AGENT_RECORDS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.synthetic-semantic-mutation', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.system-atlas-overlay', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.system-atlas-record', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.system-map-layout', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.system-map-model', persisted: false, store: 'IN_MEMORY', currentVersion: 2, versions: { 2: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.system-map-projection', persisted: false, store: 'IN_MEMORY', currentVersion: 2, versions: { 2: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.triage-compatibility.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.triage-replay-envelope.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.triage-replay-plan.private', persisted: true, store: 'PRIVATE_ARTIFACTS', currentVersion: 2, versions: { 1: 'READ_COMPATIBLE', 2: 'CURRENT', 9: 'SYNTHETIC_PROBE' }, dispositions: [{ fromVersion: 1, toVersion: 2, kind: 'READ_COMPATIBLE', fixtureId: 'triage-replay-plan-v1', reason: "validateTriageReplayPlan and the artifact reader dispatch v1 and v2." }], note: "unsupported-version probe v9 proven by the Phase 13 shadow corpus (src/core/phase13/shadow.ts)" },
  { family: 'nightwatch.untrusted-envelope', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.validation-execution-classes', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "F-PERF-2 per-file execution-class declaration; data-only, validated against mechanical detection" },
  { family: 'nightwatch.validation-lane-plan', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "F-PERF-5 declarative non-certification lane composition; data-only" },
  { family: 'nightwatch.validation-shard-plan', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "F-PERF-3 deterministic shard partition and coverage proof; data-only" },
  { family: 'nightwatch.validation-timings-report', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "F-PERF-1 rendered offline timing report; printed by bin/test-timings.mjs, never stored as authority" },
  { family: 'nightwatch.vue-sfc-extract', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.w10-campaign-yield', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.yield-denominator-semantics', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "W13 R-05 truncation floor projection; data-only, no authority" },
  { family: 'nightwatch.w10-yield-metrics', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "" },
  { family: 'nightwatch.w13-evaluation-freeze', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "W13 Phase B evaluation freeze and widened-resume guard; validation only" },
  { family: 'nightwatch.w13-current-source-yield-aggregation', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "W13 R-06 required-metric completeness contract; validation only" },
  { family: 'nightwatch.w13-run-receipt', persisted: false, store: 'IN_MEMORY', currentVersion: 1, versions: { 1: 'CURRENT' }, dispositions: [], note: "W13 R-04 per-provider attribution contract; validation only" },
];
