import {
  API_CATALOG_VERSION,
  type ApiCatalog,
  type ApiOperation,
} from './types';

export const PHASE5_SOURCE_SHAS = Object.freeze({
  rippleUi: 'd80b161b684d9153c7e5acaa65ae1752d93d8ba9',
  rippleApi: '4e3e200db3bda7b58bc250feb7f76997d95ae2cc',
  ouchan: '565f00a87fb7616cc23c45d4ffeabee38a41c65f',
  blueapi: '691422e5dc81afd263d064986fb50fcb3ea432a9',
  blueSdkGo: '8883ee3d3a073352626c8c35e20e9fc5ed765373',
  grpcChunkParser: '66802f281698dfcf0903f0a117d4637fce3fd945',
} as const);

const relayRequest = (pathTemplate: string, hydrationProfile: string, placeholders: readonly string[]) => ({
  method: 'GET' as const,
  pathTemplate,
  bodyPolicy: 'EMPTY' as const,
  hydrationProfile,
  runtimePlaceholders: placeholders,
});

const jsonOracle = (oracleId: string, shape: 'JSON_OBJECT_OR_ARRAY' | 'JSON_CHUNKS' = 'JSON_OBJECT_OR_ARRAY') => ({
  oracleId,
  expectedContentType: 'application/json' as const,
  shape,
  persistBody: false as const,
  maxBytes: 2 * 1024 * 1024,
});

const operations: readonly ApiOperation[] = [
  {
    operationId: 'ripple.payer-exchange.read',
    product: 'ripple',
    service: 'ripple-api',
    sourceRepo: 'mobingilabs/ripple-api',
    sourceSHA: PHASE5_SOURCE_SHAS.rippleApi,
    frontendCallsites: ['mobingilabs/ripple-ui:src/vuex/api/exchangeRatePayer_v2.js:actions.fetch'],
    httpMethod: 'GET',
    pathTemplate: '/m/ripple/v2/payer/exchange_rate/${NW_RUNTIME_PERIOD}',
    semanticPurpose: 'Read payer-level exchange rates for the source-selected month.',
    semanticClass: 'KNOWN_READ',
    authClass: 'RELAY_EPHEMERAL_DEV_SESSION',
    requestSchema: relayRequest('/m/ripple/v2/payer/exchange_rate/${NW_RUNTIME_PERIOD}', 'source-approved-current-period', ['${NW_RUNTIME_PERIOD}']),
    safeHydrationStrategy: 'Use a bounded YYYY-MM period selected in memory; never persist the resolved period with customer scope.',
    responseShapePolicy: jsonOracle('ripple.payer-exchange.read.json'),
    streamingType: 'SINGLE_JSON',
    expectedContentType: 'application/json',
    requiredHostClass: 'DEV_API',
    oracleProfile: 'ripple.payer-exchange.read.json',
    replayPolicy: 'FIRST_PLUS_FRESH_REPLAY',
    sourceProvenance: [
      `mobingilabs/ripple-ui@${PHASE5_SOURCE_SHAS.rippleUi}:src/vuex/api/exchangeRatePayer_v2.js GET`,
      `mobingilabs/ripple-api@${PHASE5_SOURCE_SHAS.rippleApi}:src/App/Route/Config/Routing.yaml get:/v2/payer/exchange_rate/{month}`,
      `mobingilabs/ripple-api@${PHASE5_SOURCE_SHAS.rippleApi}:src/App/Handler/ExchangeRate.php getAccountExchangeForMonth`,
    ],
    journeyLinks: ['ripple-payer-exchange-read'],
    generationStatus: 'GENERATION_ELIGIBLE',
  },
  {
    operationId: 'ripple.common-exchange.read',
    product: 'ripple',
    service: 'ripple-api',
    sourceRepo: 'mobingilabs/ripple-api',
    sourceSHA: PHASE5_SOURCE_SHAS.rippleApi,
    frontendCallsites: ['mobingilabs/ripple-ui:src/vuex/api/exchangeRateGlobal.js:actions.fetch'],
    httpMethod: 'GET',
    pathTemplate: '/m/ripple/exchange_rate/global/${NW_RUNTIME_VENDOR}',
    semanticPurpose: 'Read common exchange rates for a fixed source-defined vendor enum.',
    semanticClass: 'KNOWN_READ',
    authClass: 'RELAY_EPHEMERAL_DEV_SESSION',
    requestSchema: relayRequest('/m/ripple/exchange_rate/global/${NW_RUNTIME_VENDOR}', 'source-defined-vendor-enum', ['${NW_RUNTIME_VENDOR}']),
    safeHydrationStrategy: 'Use only aws or azure, selected from the source-defined vendor enum; no customer value is resolved.',
    responseShapePolicy: jsonOracle('ripple.common-exchange.read.json'),
    streamingType: 'SINGLE_JSON',
    expectedContentType: 'application/json',
    requiredHostClass: 'DEV_API',
    oracleProfile: 'ripple.common-exchange.read.json',
    replayPolicy: 'FIRST_PLUS_FRESH_REPLAY',
    sourceProvenance: [
      `mobingilabs/ripple-ui@${PHASE5_SOURCE_SHAS.rippleUi}:src/vuex/api/exchangeRateGlobal.js GET`,
      `mobingilabs/ripple-api@${PHASE5_SOURCE_SHAS.rippleApi}:src/App/Route/Config/Routing.yaml get:/exchange_rate/global/{vendor}`,
      `mobingilabs/ripple-api@${PHASE5_SOURCE_SHAS.rippleApi}:src/App/Handler/ExchangeRate.php getCommonExchangeRate`,
    ],
    journeyLinks: ['ripple-common-exchange-read'],
    generationStatus: 'GENERATION_ELIGIBLE',
  },
  {
    operationId: 'ripple.account-inventory.read',
    product: 'ripple',
    service: 'ripple-api',
    sourceRepo: 'mobingilabs/ripple-api',
    sourceSHA: PHASE5_SOURCE_SHAS.rippleApi,
    frontendCallsites: ['mobingilabs/ripple-ui:src/vuex/api/accounts.js:actions.fetchAccounts'],
    httpMethod: 'GET',
    pathTemplate: '/m/ripple/accts',
    semanticPurpose: 'Read the authenticated account inventory using a fixed vendor filter.',
    semanticClass: 'KNOWN_READ',
    authClass: 'RELAY_EPHEMERAL_DEV_SESSION',
    requestSchema: {
      ...relayRequest('/m/ripple/accts', 'source-defined-vendor-enum', []),
      queryTemplate: { vendor: 'aws' },
    },
    safeHydrationStrategy: 'Use fixed query vendor=aws; response identifiers remain in memory and are never recorded.',
    responseShapePolicy: jsonOracle('ripple.account-inventory.read.json'),
    streamingType: 'SINGLE_JSON',
    expectedContentType: 'application/json',
    requiredHostClass: 'DEV_API',
    oracleProfile: 'ripple.account-inventory.read.json',
    replayPolicy: 'FIRST_PLUS_FRESH_REPLAY',
    sourceProvenance: [
      `mobingilabs/ripple-ui@${PHASE5_SOURCE_SHAS.rippleUi}:src/vuex/api/accounts.js GET /accts`,
      `mobingilabs/ripple-api@${PHASE5_SOURCE_SHAS.rippleApi}:src/App/Route/Config/Routing.yaml get:/accts`,
      `mobingilabs/ripple-api@${PHASE5_SOURCE_SHAS.rippleApi}:src/App/Handler/Account.php getAccountVendor`,
    ],
    journeyLinks: ['ripple-account-inventory'],
    generationStatus: 'GENERATION_ELIGIBLE',
    notes: ['The response can contain customer/account identifiers; only metadata/shape oracles are allowed.'],
  },
  {
    operationId: 'ripple.billing-groups.read',
    product: 'ripple',
    service: 'blue-billing',
    sourceRepo: 'mobingilabs/ouchan',
    sourceSHA: PHASE5_SOURCE_SHAS.ouchan,
    frontendCallsites: ['mobingilabs/ripple-ui:src/vuex/api/billingGroups.js:actions.fetch'],
    protoService: 'alphaus.billing.v1.Billing',
    protoRPC: 'ListBillingGroups',
    httpMethod: 'GET',
    pathTemplate: '/m/blue/billing/v1/billinggroups',
    semanticPurpose: 'Read the authenticated billing-group stream used by the account inventory surface.',
    semanticClass: 'KNOWN_READ',
    authClass: 'RELAY_EPHEMERAL_DEV_SESSION',
    requestSchema: relayRequest('/m/blue/billing/v1/billinggroups', 'empty-read-request', []),
    safeHydrationStrategy: 'Empty GET request; no customer-specific filter is written to the corpus.',
    responseShapePolicy: jsonOracle('ripple.billing-groups.read.chunked-json', 'JSON_CHUNKS'),
    streamingType: 'JSON_CHUNKED',
    expectedContentType: 'application/json',
    requiredHostClass: 'DEV_API',
    oracleProfile: 'ripple.billing-groups.read.chunked-json',
    replayPolicy: 'FIRST_PLUS_FRESH_REPLAY',
    sourceProvenance: [
      `mobingilabs/ripple-ui@${PHASE5_SOURCE_SHAS.rippleUi}:src/vuex/api/billingGroups.js streamPromise GET`,
      `mobingilabs/ripple-ui@${PHASE5_SOURCE_SHAS.rippleUi}:src/vuex/api/admin.js parseGrpcData/streamPromise`,
      `mobingilabs/ouchan@${PHASE5_SOURCE_SHAS.ouchan}:services/billingd/services/billingsvc/billingsvc.go ListBillingGroups`,
      `alphauslabs/blueapi@${PHASE5_SOURCE_SHAS.blueapi}:billing/v1/billing.proto ListBillingGroups`,
      `alphauslabs/grpc-chunk-parser@${PHASE5_SOURCE_SHAS.grpcChunkParser}:src/`,
    ],
    journeyLinks: ['ripple-account-inventory'],
    generationStatus: 'GENERATION_ELIGIBLE',
    notes: ['Behavioral equivalence is stream/status/content-type/shape metadata only; response values are not compared.'],
  },
  {
    operationId: 'ripple.billing-groups-legacy.read',
    product: 'ripple',
    service: 'ripple-api',
    sourceRepo: 'mobingilabs/ripple-api',
    sourceSHA: PHASE5_SOURCE_SHAS.rippleApi,
    frontendCallsites: ['mobingilabs/ripple-ui:src/vuex/api/billingGroups.js:actions.fetchBillingGroupsLegacy'],
    httpMethod: 'GET',
    pathTemplate: '/m/ripple/billinggroup',
    semanticPurpose: 'Read the legacy billing-group/account view with a fixed vendor filter.',
    semanticClass: 'KNOWN_READ',
    authClass: 'RELAY_EPHEMERAL_DEV_SESSION',
    requestSchema: {
      ...relayRequest('/m/ripple/billinggroup', 'source-defined-vendor-enum', []),
      queryTemplate: { filter_vendor: 'aws' },
    },
    safeHydrationStrategy: 'Use fixed query filter_vendor=aws; response identifiers are in-memory only.',
    responseShapePolicy: jsonOracle('ripple.billing-groups-legacy.read.json'),
    streamingType: 'SINGLE_JSON',
    expectedContentType: 'application/json',
    requiredHostClass: 'DEV_API',
    oracleProfile: 'ripple.billing-groups-legacy.read.json',
    replayPolicy: 'FIRST_PLUS_FRESH_REPLAY',
    sourceProvenance: [
      `mobingilabs/ripple-ui@${PHASE5_SOURCE_SHAS.rippleUi}:src/vuex/api/billingGroups.js fetchBillingGroupsLegacy`,
      `mobingilabs/ripple-api@${PHASE5_SOURCE_SHAS.rippleApi}:src/App/Route/Config/Routing.yaml get:/billinggroup`,
      `mobingilabs/ripple-api@${PHASE5_SOURCE_SHAS.rippleApi}:src/App/Handler/BillingGroup.php getBillingGroupAccount`,
    ],
    journeyLinks: [],
    generationStatus: 'GENERATION_ELIGIBLE',
    notes: ['API-only expansion; source handler reads cache/DB and applies read RBAC filtering.'],
  },
  {
    operationId: 'ripple.billing-group-exchange.read',
    product: 'ripple',
    service: 'ripple-api',
    sourceRepo: 'mobingilabs/ripple-api',
    sourceSHA: PHASE5_SOURCE_SHAS.rippleApi,
    frontendCallsites: [],
    httpMethod: 'GET',
    pathTemplate: '/m/ripple/exchange_rate/billing_group/${NW_RUNTIME_PERIOD}',
    semanticPurpose: 'Read billing-group exchange-rate settings for a bounded source-approved month.',
    semanticClass: 'KNOWN_READ',
    authClass: 'RELAY_EPHEMERAL_DEV_SESSION',
    requestSchema: relayRequest('/m/ripple/exchange_rate/billing_group/${NW_RUNTIME_PERIOD}', 'source-approved-current-period', ['${NW_RUNTIME_PERIOD}']),
    safeHydrationStrategy: 'Use a bounded YYYY-MM period selected in memory; no billing-group identifier is supplied.',
    responseShapePolicy: jsonOracle('ripple.billing-group-exchange.read.json'),
    streamingType: 'SINGLE_JSON',
    expectedContentType: 'application/json',
    requiredHostClass: 'DEV_API',
    oracleProfile: 'ripple.billing-group-exchange.read.json',
    replayPolicy: 'FIRST_PLUS_FRESH_REPLAY',
    sourceProvenance: [
      `mobingilabs/ripple-api@${PHASE5_SOURCE_SHAS.rippleApi}:src/App/Route/Config/Routing.yaml get:/exchange_rate/billing_group/{month}`,
      `mobingilabs/ripple-api@${PHASE5_SOURCE_SHAS.rippleApi}:src/App/Handler/BillingGroup.php getExchangeRateForBillingGroup`,
    ],
    journeyLinks: [],
    generationStatus: 'GENERATION_ELIGIBLE',
    notes: ['API-only expansion; no UI canary is claimed for this operation.'],
  },
  {
    operationId: 'ripple.payer-exchange.write',
    product: 'ripple',
    service: 'ripple-api',
    sourceRepo: 'mobingilabs/ripple-api',
    sourceSHA: PHASE5_SOURCE_SHAS.rippleApi,
    frontendCallsites: ['mobingilabs/ripple-ui:src/vuex/api/exchangeRatePayer_v2.js:actions.post'],
    httpMethod: 'POST',
    pathTemplate: '/m/ripple/v2/payer/exchange_rate/${NW_RUNTIME_PERIOD}',
    semanticPurpose: 'Persist payer exchange-rate settings.',
    semanticClass: 'KNOWN_MUTATION',
    authClass: 'UNAVAILABLE',
    streamingType: 'UNKNOWN',
    requiredHostClass: 'PRODUCTION_DENIED',
    replayPolicy: 'NEVER',
    sourceProvenance: [`mobingilabs/ripple-api@${PHASE5_SOURCE_SHAS.rippleApi}:src/App/Handler/ExchangeRate.php saveAccountExchangeForMonth`],
    journeyLinks: ['ripple-payer-exchange-read'],
    generationStatus: 'GENERATION_BLOCKED',
  },
  {
    operationId: 'ripple.common-exchange.write',
    product: 'ripple',
    service: 'ripple-api',
    sourceRepo: 'mobingilabs/ripple-api',
    sourceSHA: PHASE5_SOURCE_SHAS.rippleApi,
    frontendCallsites: ['mobingilabs/ripple-ui:src/vuex/api/exchangeRateGlobal.js:actions.post'],
    httpMethod: 'POST',
    pathTemplate: '/m/ripple/exchange_rate/global/${NW_RUNTIME_VENDOR}/${NW_RUNTIME_PERIOD}',
    semanticPurpose: 'Create or update common exchange-rate settings.',
    semanticClass: 'KNOWN_MUTATION',
    authClass: 'UNAVAILABLE',
    streamingType: 'UNKNOWN',
    requiredHostClass: 'PRODUCTION_DENIED',
    replayPolicy: 'NEVER',
    sourceProvenance: [`mobingilabs/ripple-api@${PHASE5_SOURCE_SHAS.rippleApi}:src/App/Handler/ExchangeRate.php setCommonExchangeRate`],
    journeyLinks: ['ripple-common-exchange-read'],
    generationStatus: 'GENERATION_BLOCKED',
  },
  {
    operationId: 'ripple.account-inventory.write',
    product: 'ripple',
    service: 'ripple-api',
    sourceRepo: 'mobingilabs/ripple-api',
    sourceSHA: PHASE5_SOURCE_SHAS.rippleApi,
    frontendCallsites: ['mobingilabs/ripple-ui:src/vuex/api/accounts.js:actions.postAccount/patchAccount/deleteAccount'],
    httpMethod: 'POST',
    pathTemplate: '/m/ripple/accts/${NW_RUNTIME_RESOURCE_ID}',
    semanticPurpose: 'Create, edit, or delete a cloud account.',
    semanticClass: 'KNOWN_MUTATION',
    authClass: 'UNAVAILABLE',
    streamingType: 'UNKNOWN',
    requiredHostClass: 'PRODUCTION_DENIED',
    replayPolicy: 'NEVER',
    sourceProvenance: [`mobingilabs/ripple-api@${PHASE5_SOURCE_SHAS.rippleApi}:src/App/Route/Config/Routing.yaml POST/PUT/DELETE /accts routes`],
    journeyLinks: ['ripple-account-inventory'],
    generationStatus: 'GENERATION_BLOCKED',
  },
  {
    operationId: 'ripple.billing-group-exchange.write',
    product: 'ripple',
    service: 'ripple-api',
    sourceRepo: 'mobingilabs/ripple-api',
    sourceSHA: PHASE5_SOURCE_SHAS.rippleApi,
    frontendCallsites: [],
    httpMethod: 'POST',
    pathTemplate: '/m/ripple/exchange_rate/billing_group/${NW_RUNTIME_PERIOD}',
    semanticPurpose: 'Update billing-group exchange-rate settings.',
    semanticClass: 'KNOWN_MUTATION',
    authClass: 'UNAVAILABLE',
    streamingType: 'UNKNOWN',
    requiredHostClass: 'PRODUCTION_DENIED',
    replayPolicy: 'NEVER',
    sourceProvenance: [`mobingilabs/ripple-api@${PHASE5_SOURCE_SHAS.rippleApi}:src/App/Handler/BillingGroup.php updateExchangeRateForBillingGroup`],
    journeyLinks: [],
    generationStatus: 'GENERATION_BLOCKED',
  },
  {
    operationId: 'ripple.historical-blue-cost.unknown',
    product: 'ripple',
    service: 'blue-cost',
    sourceRepo: 'alphauslabs/blueapi',
    sourceSHA: PHASE5_SOURCE_SHAS.blueapi,
    frontendCallsites: [],
    httpMethod: 'POST',
    pathTemplate: '/m/blue/cost/v1/',
    semanticPurpose: 'Historical malformed-JSON observation; current source semantics are not independently proven in this phase.',
    semanticClass: 'UNKNOWN',
    authClass: 'UNAVAILABLE',
    streamingType: 'UNKNOWN',
    requiredHostClass: 'UNKNOWN_HOST',
    replayPolicy: 'NEVER',
    sourceProvenance: ['Phase 2A/2C historical protocol evidence only; no current handler admission'],
    journeyLinks: [],
    generationStatus: 'SEMANTIC_REVIEW_REQUIRED',
    notes: ['HISTORICAL_ANOMALY_PRESENT; do not generate or deliberately replay in Phase 5.'],
  },
];

export const PHASE5_API_CATALOG: ApiCatalog = Object.freeze({
  schemaVersion: API_CATALOG_VERSION,
  generatedBy: 'nightwatch.scenario-generator.phase5.v1',
  operations,
});

export function getPhase5Operation(operationId: string): ApiOperation {
  const operation = PHASE5_API_CATALOG.operations.find((candidate) => candidate.operationId === operationId);
  if (!operation) throw new Error(`fail-closed: unknown Phase 5 API operation "${operationId}"`);
  return operation;
}

export function phase5CatalogCounts(): Record<string, number> {
  const counts = { inventoried: operations.length, KNOWN_READ: 0, KNOWN_MUTATION: 0, UNKNOWN: 0, generationEligible: 0, generated: 0, localOopsVerified: 0, devFirst: 0, devReplay: 0, blocked: 0, anomalous: 0 };
  for (const operation of operations) {
    counts[operation.semanticClass] += 1;
    if (operation.generationStatus === 'GENERATION_ELIGIBLE') counts.generationEligible += 1;
    if (operation.generationStatus !== 'GENERATION_ELIGIBLE') counts.blocked += 1;
  }
  return counts;
}
