// ---------------------------------------------------------------------------
// Nightwatch Phase 11A.1 — receipt closeout permanent tests.
//
// The Phase 11A.1 defect was: semantic PARTIAL_COVERAGE mapped to receipt PASS.
// The fix adds PARTIAL_COVERAGE to the receipt outcome vocabulary, makes it
// non-pass, and adds coverage coherence validation.
//
// These permanent tests lock down every contractual requirement from the
// Phase 11A.1 SPEC and prevent regression.
//
// All fixtures are SYNTHETIC ONLY. No real customer data.
// ---------------------------------------------------------------------------

import { expect, test } from '@playwright/test';
import {
  buildSemanticEvaluationReceipt,
  validateSemanticEvaluationReceipt,
  SEMANTIC_RECEIPT_NON_PASS_OUTCOMES,
  SEMANTIC_RECEIPT_OUTCOMES,
  SEMANTIC_EVALUATION_RECEIPT_VERSION,
  SEMANTIC_EVALUATION_RECEIPT_VERSION_V1,
} from '../../src/oracles/semantic/receipts';
import { semanticOutcomeToReceiptOutcome } from '../../src/oracles/semantic/hook';
import { evaluateSemanticResponse } from '../../src/oracles/semantic';
import type { SemanticExpectation } from '../../src/oracles/expectations/types';
import { DEFAULT_PROJECTION_LIMITS } from '../../src/oracles/projections';
import {
  SENTINEL,
  generateExchangeArray,
  validExchangeItem,
} from '../../corpus/phase11/response-fixtures';
import {
  createCollectionItemContract,
  createCollectionExpectation,
  PHASE11_FIXTURE_SHA,
  PHASE11_PROVENANCE,
} from '../../corpus/phase11/source-fixture/phase11Fixtures';

// ---------------------------------------------------------------------------
// Test constants.
// ---------------------------------------------------------------------------

const FIXTURE_SHA = PHASE11_FIXTURE_SHA;
const ORACLE_ID = 'oracle.semantic.phase11a1.receipt-closeout';
const JOURNEY_ID = 'phase11a1.synthetic.journey';
const STEP_ID = 'phase11a1.synthetic.step';

// ---------------------------------------------------------------------------
// Helpers.
// ---------------------------------------------------------------------------

/** Build a TYPE_MATCH collection-item contract for the `month` field. */
function monthTypeContract() {
  return createCollectionItemContract([], 'TYPE_MATCH', ['month'], {
    itemExpectedType: 'STRING',
  });
}

/** Create a collection-wide TYPE_MATCH expectation. */
function collectionExpectation(
  contracts = [monthTypeContract()],
): SemanticExpectation {
  return createCollectionExpectation(
    'ripple.common-exchange.read.real-source-collection',
    contracts,
  );
}

/** Run a collection-wide evaluation. */
function evaluateCollection(
  responseBody: unknown,
  expectation: SemanticExpectation,
  snapshotSha: string | null = FIXTURE_SHA,
) {
  return evaluateSemanticResponse({
    oracleId: ORACLE_ID,
    expectation,
    rawValues: [responseBody],
    sourceSnapshot: snapshotSha === null ? null : { repoId: PHASE11_PROVENANCE.repoId, sha: snapshotSha },
    journeyId: JOURNEY_ID,
    stepId: STEP_ID,
    operationId: expectation.targetId,
  });
}

/** Sweep a JSON-serializable value for raw sentinel leaks. */
function sweepForSentinelLeaks(value: unknown): string[] {
  const leaks: string[] = [];
  const text = JSON.stringify(value);
  const sentinels = [
    SENTINEL.MONTH, SENTINEL.RATE, SENTINEL.NAME,
    SENTINEL.ID, SENTINEL.NUMBER, String(SENTINEL.WRONG_TYPE),
  ];
  for (const s of sentinels) {
    if (text.includes(s)) leaks.push(s);
  }
  return leaks;
}

// ===========================================================================
// 1. Receipt outcome mapping — PARTIAL_COVERAGE round-trips correctly.
// ===========================================================================

test.describe('Phase 11A.1 §1: receipt outcome mapping', () => {
  test('semanticOutcomeToReceiptOutcome maps PARTIAL_COVERAGE to PARTIAL_COVERAGE', () => {
    expect(semanticOutcomeToReceiptOutcome('PARTIAL_COVERAGE')).toBe('PARTIAL_COVERAGE');
  });

  test('PARTIAL_COVERAGE is in SEMANTIC_RECEIPT_NON_PASS_OUTCOMES', () => {
    expect(SEMANTIC_RECEIPT_NON_PASS_OUTCOMES.has('PARTIAL_COVERAGE')).toBe(true);
  });

  test('PASS is NOT in SEMANTIC_RECEIPT_NON_PASS_OUTCOMES', () => {
    expect(SEMANTIC_RECEIPT_NON_PASS_OUTCOMES.has('PASS')).toBe(false);
  });

  test('PARTIAL_COVERAGE is in the full SEMANTIC_RECEIPT_OUTCOMES list', () => {
    expect(SEMANTIC_RECEIPT_OUTCOMES).toContain('PARTIAL_COVERAGE');
  });

  test('every semantic non-pass outcome maps correctly through the hook', () => {
    // semanticOutcomeToReceiptOutcome takes SEMANTIC outcomes, not receipt
    // outcomes. Receipt-level concepts like NO_EXPECTATION are not semantic
    // outcomes and fall to INTERNAL_ERROR via the default case. Verify that
    // the core semantic outcomes (the ones generated by the runner) map to
    // their expected receipt counterparts.
    const semanticToReceipt: Array<[string, string]> = [
      ['PASS', 'PASS'],
      ['ANOMALY', 'ANOMALY'],
      ['NOT_APPLICABLE', 'NOT_APPLICABLE'],
      ['PARTIAL_COVERAGE', 'PARTIAL_COVERAGE'],
      ['EXPECTATION_UNAVAILABLE', 'EXPECTATION_SOURCE_UNAVAILABLE'],
      ['EXPECTATION_SOURCE_STALE', 'EXPECTATION_SOURCE_STALE'],
      ['INVALID_INPUT', 'INVALID_INPUT'],
      ['PROJECTION_LIMIT_EXCEEDED', 'PROJECTION_LIMIT_EXCEEDED'],
      ['EXPECTATION_INVALID', 'INTERNAL_ERROR'],
    ];
    for (const [semantic, receipt] of semanticToReceipt) {
      expect(semanticOutcomeToReceiptOutcome(semantic)).toBe(receipt);
    }
    // Unknown semantic outcomes fall to INTERNAL_ERROR.
    expect(semanticOutcomeToReceiptOutcome('UNKNOWN_XYZ')).toBe('INTERNAL_ERROR');
  });
});

// ===========================================================================
// 2. End-to-end receipt for 129 valid rows.
// ===========================================================================

test.describe('Phase 11A.1 §2: 129 valid rows produce PARTIAL_COVERAGE receipt', () => {
  test('129 valid exchange items evaluate to PARTIAL_COVERAGE and build receipt PARTIAL_COVERAGE', () => {
    const body = generateExchangeArray(129);
    const expectation = collectionExpectation();
    const result = evaluateCollection(body, expectation);

    // Semantic outcome must be PARTIAL_COVERAGE (129 > 128 projection cap).
    expect(result.outcome).toBe('PARTIAL_COVERAGE');
    const ev = result.invariantEvaluations.find(e => e.invariantKind === 'COLLECTION_ITEM_CONTRACT');
    expect(ev).toBeDefined();
    expect(ev!.verdict).toBe('PASS');
    expect(ev!.coverageState).toBe('PARTIAL_COVERAGE_NO_VIOLATION');
    expect(ev!.inspectedItemCount).toBe(128);
    expect(ev!.violatingItemCount).toBe(0);

    // Build receipt from the evaluation and verify it is PARTIAL_COVERAGE.
    const receipt = buildSemanticEvaluationReceipt({
      oracleId: ORACLE_ID,
      outcome: 'PARTIAL_COVERAGE',
      expectationId: expectation.expectationId,
      sourceProvenance: expectation.sourceProvenance,
      invariantTotal: 1,
      invariantPassCount: 1,
      invariantNaCount: 0,
      invariantViolationCount: 0,
      findingCount: 0,
      coverageState: 'PARTIAL_COVERAGE_NO_VIOLATION',
      inspectedItemCount: 128,
      violatingItemCount: 0,
      journeyId: JOURNEY_ID,
      stepId: STEP_ID,
      operationId: expectation.targetId,
    });

    expect(receipt.outcome).toBe('PARTIAL_COVERAGE');
    expect(receipt.coverageState).toBe('PARTIAL_COVERAGE_NO_VIOLATION');
    expect(receipt.inspectedItemCount).toBe(128);
    expect(receipt.violatingItemCount).toBe(0);
  });
});

// ===========================================================================
// 3. First-uninspected-row defect — 129 rows, defect at row 128.
// ===========================================================================

test.describe('Phase 11A.1 §3: first-uninspected-row defect remains PARTIAL_COVERAGE', () => {
  test('129 items with defect at row 128 produce PARTIAL_COVERAGE (not PASS/anomaly)', () => {
    // 129 items, rows 0..127 valid, row 128 has wrong type — but row 128
    // is beyond the 128-item projection cap, so it is unobservable.
    const body = Array.from({ length: 129 }, (_, i) => {
      if (i === 128) return { month: SENTINEL.WRONG_TYPE, exchange_rate: { usd: 1.0 } };
      return validExchangeItem(i);
    });
    const expectation = collectionExpectation();
    const result = evaluateCollection(body, expectation);

    expect(result.outcome).toBe('PARTIAL_COVERAGE');
    const ev = result.invariantEvaluations.find(e => e.invariantKind === 'COLLECTION_ITEM_CONTRACT');
    expect(ev!.coverageState).toBe('PARTIAL_COVERAGE_NO_VIOLATION');
    expect(ev!.inspectedItemCount).toBe(128);
    expect(ev!.violatingItemCount).toBe(0);
    // Must NOT be PASS or ANOMALY.
    expect(result.outcome).not.toBe('PASS');
    expect(result.outcome).not.toBe('ANOMALY');
  });
});

// ===========================================================================
// 4. Truncated + observed violation remains ANOMALY with coverage VIOLATION.
// ===========================================================================

test.describe('Phase 11A.1 §4: truncated + observed violation stays ANOMALY', () => {
  test('130 items with defect at row 57 produces ANOMALY with VIOLATION coverage', () => {
    const body = Array.from({ length: 130 }, (_, i) => {
      if (i === 57) return { month: SENTINEL.WRONG_TYPE, exchange_rate: { usd: 1.0 } };
      return validExchangeItem(i);
    });
    const expectation = collectionExpectation();
    const result = evaluateCollection(body, expectation);

    expect(result.outcome).toBe('ANOMALY');
    const ev = result.invariantEvaluations.find(e => e.invariantKind === 'COLLECTION_ITEM_CONTRACT');
    expect(ev!.verdict).toBe('VIOLATED');
    expect(ev!.coverageState).toBe('VIOLATION');
    expect(ev!.inspectedItemCount).toBe(128);
    expect(ev!.violatingItemCount).toBe(1);
    expect(ev!.firstViolationOrdinal).toBe(57);
  });
});

// ===========================================================================
// 5. Non-truncated all-valid (128 items) remains PASS + FULLY_EVALUATED_PASS.
// ===========================================================================

test.describe('Phase 11A.1 §5: exactly 128 valid items stays PASS', () => {
  test('128 valid items evaluate to PASS with FULLY_EVALUATED_PASS coverage', () => {
    const body = generateExchangeArray(128);
    const expectation = collectionExpectation();
    const result = evaluateCollection(body, expectation);

    expect(result.outcome).toBe('PASS');
    const ev = result.invariantEvaluations.find(e => e.invariantKind === 'COLLECTION_ITEM_CONTRACT');
    expect(ev!.verdict).toBe('PASS');
    expect(ev!.coverageState).toBe('FULLY_EVALUATED_PASS');
    expect(ev!.inspectedItemCount).toBe(128);
    expect(ev!.violatingItemCount).toBe(0);
  });
});

// ===========================================================================
// 6. Empty collection remains benign / NOT_APPLICABLE, not anomaly.
// ===========================================================================

test.describe('Phase 11A.1 §6: empty collection stays benign', () => {
  test('empty array evaluates to NOT_APPLICABLE (not anomaly)', () => {
    const expectation = collectionExpectation();
    const result = evaluateCollection([], expectation);

    expect(result.outcome).toBe('NOT_APPLICABLE');
    expect(result.findings).toHaveLength(0);
    const ev = result.invariantEvaluations.find(e => e.invariantKind === 'COLLECTION_ITEM_CONTRACT');
    expect(ev!.verdict).toBe('NOT_APPLICABLE');
    expect(ev!.coverageState).toBe('EMPTY_NOT_APPLICABLE');
  });
});

// ===========================================================================
// 7. Receipt coherence — PASS + partial coverage metadata rejected.
// ===========================================================================

test.describe('Phase 11A.1 §7: PASS + partial coverage metadata rejected', () => {
  test('building a PASS receipt with PARTIAL_COVERAGE_NO_VIOLATION coverageState throws', () => {
    expect(() => {
      buildSemanticEvaluationReceipt({
        oracleId: ORACLE_ID,
        outcome: 'PASS',
        expectationId: 'ripple.common-exchange.read.real-source-collection',
        sourceProvenance: PHASE11_PROVENANCE,
        invariantTotal: 1,
        invariantPassCount: 1,
        invariantNaCount: 0,
        invariantViolationCount: 0,
        findingCount: 0,
        coverageState: 'PARTIAL_COVERAGE_NO_VIOLATION',
        inspectedItemCount: 129,
        violatingItemCount: 0,
      });
    }).toThrow('SEMANTIC_RECEIPT_INVALID:pass-with-partial-coverage');
  });
});

// ===========================================================================
// 8. Receipt coherence — PARTIAL_COVERAGE without coverage state rejected.
// ===========================================================================

test.describe('Phase 11A.1 §8: PARTIAL_COVERAGE without coverage state rejected', () => {
  test('building a PARTIAL_COVERAGE receipt without coverageState throws', () => {
    expect(() => {
      buildSemanticEvaluationReceipt({
        oracleId: ORACLE_ID,
        outcome: 'PARTIAL_COVERAGE',
        expectationId: 'ripple.common-exchange.read.real-source-collection',
        sourceProvenance: PHASE11_PROVENANCE,
        invariantTotal: 1,
        invariantPassCount: 1,
        invariantNaCount: 0,
        invariantViolationCount: 0,
        findingCount: 0,
        // coverageState intentionally omitted
      });
    }).toThrow('SEMANTIC_RECEIPT_INVALID:partial-coverage-requires-coverage-state');
  });

  test('building a PARTIAL_COVERAGE receipt with VIOLATION coverageState throws', () => {
    expect(() => {
      buildSemanticEvaluationReceipt({
        oracleId: ORACLE_ID,
        outcome: 'PARTIAL_COVERAGE',
        expectationId: 'ripple.common-exchange.read.real-source-collection',
        sourceProvenance: PHASE11_PROVENANCE,
        invariantTotal: 1,
        invariantPassCount: 1,
        invariantNaCount: 0,
        invariantViolationCount: 0,
        findingCount: 0,
        coverageState: 'VIOLATION',
        inspectedItemCount: 128,
        violatingItemCount: 0,
      });
    }).toThrow('SEMANTIC_RECEIPT_INVALID:partial-coverage-requires-coverage-state');
  });
});

// ===========================================================================
// 9. violatingItemCount > inspectedItemCount rejected.
// ===========================================================================

test.describe('Phase 11A.1 §9: violatingItemCount > inspectedItemCount rejected', () => {
  test('violatingItemCount exceeding inspectedItemCount throws', () => {
    expect(() => {
      buildSemanticEvaluationReceipt({
        oracleId: ORACLE_ID,
        outcome: 'ANOMALY',
        invariantTotal: 1,
        invariantPassCount: 0,
        invariantNaCount: 0,
        invariantViolationCount: 1,
        findingCount: 1,
        coverageState: 'VIOLATION',
        inspectedItemCount: 10,
        violatingItemCount: 11,
      });
    }).toThrow('SEMANTIC_RECEIPT_INVALID:violating-exceeds-inspected');
  });
});

// ===========================================================================
// 10. v1 receipt with v2 coverage fields rejected.
// ===========================================================================

test.describe('Phase 11A.1 §10: v1 receipt with v2 coverage fields rejected', () => {
  test('v1 receipt with ANOMALY outcome and VIOLATION coverageState throws', () => {
    // ANOMALY + VIOLATION is a valid v2 combination; the v1 check catches
    // that coverage fields must not appear on v1 receipts.
    const v1Receipt = {
      schemaVersion: SEMANTIC_EVALUATION_RECEIPT_VERSION_V1,
      receiptId: 'receipt:sha256:000000000000000000000000',
      oracleId: ORACLE_ID,
      outcome: 'ANOMALY' as const,
      projectionDigests: [] as string[],
      invariantTotal: 1,
      invariantPassCount: 0,
      invariantNaCount: 0,
      invariantViolationCount: 1,
      findingCount: 1,
      coverageState: 'VIOLATION' as const,
      inspectedItemCount: 128,
      violatingItemCount: 1,
    } as unknown as Parameters<typeof validateSemanticEvaluationReceipt>[0];

    expect(() => {
      validateSemanticEvaluationReceipt(v1Receipt);
    }).toThrow('SEMANTIC_RECEIPT_INVALID:v1-coverage-fields');
  });

  test('v1 receipt with inspectedItemCount throws', () => {
    const v1Receipt = {
      schemaVersion: SEMANTIC_EVALUATION_RECEIPT_VERSION_V1,
      receiptId: 'receipt:sha256:000000000000000000000000',
      oracleId: ORACLE_ID,
      outcome: 'PASS' as const,
      projectionDigests: [] as string[],
      invariantTotal: 1,
      invariantPassCount: 1,
      invariantNaCount: 0,
      invariantViolationCount: 0,
      findingCount: 0,
      inspectedItemCount: 128,
    } as unknown as Parameters<typeof validateSemanticEvaluationReceipt>[0];

    expect(() => {
      validateSemanticEvaluationReceipt(v1Receipt);
    }).toThrow('SEMANTIC_RECEIPT_INVALID:v1-coverage-fields');
  });

  test('v1 receipt with PARTIAL_COVERAGE outcome and coverage fields throws', () => {
    // Include the required coverageState to pass the PARTIAL_COVERAGE
    // coherence check; the v1 check then catches the coverage fields.
    const v1Receipt = {
      schemaVersion: SEMANTIC_EVALUATION_RECEIPT_VERSION_V1,
      receiptId: 'receipt:sha256:000000000000000000000000',
      oracleId: ORACLE_ID,
      outcome: 'PARTIAL_COVERAGE' as const,
      projectionDigests: [] as string[],
      invariantTotal: 1,
      invariantPassCount: 1,
      invariantNaCount: 0,
      invariantViolationCount: 0,
      findingCount: 0,
      coverageState: 'PARTIAL_COVERAGE_NO_VIOLATION' as const,
      inspectedItemCount: 128,
      violatingItemCount: 0,
    } as unknown as Parameters<typeof validateSemanticEvaluationReceipt>[0];

    expect(() => {
      validateSemanticEvaluationReceipt(v1Receipt);
    }).toThrow('SEMANTIC_RECEIPT_INVALID:v1-coverage-fields');
  });
});

// ===========================================================================
// 11. Historical v1 receipt without coverage fields remains valid.
// ===========================================================================

test.describe('Phase 11A.1 §11: historical v1 receipt without coverage fields valid', () => {
  test('v1 PASS receipt without coverage fields validates successfully', () => {
    const v1Receipt = {
      schemaVersion: SEMANTIC_EVALUATION_RECEIPT_VERSION_V1,
      receiptId: 'receipt:sha256:000000000000000000000000',
      oracleId: ORACLE_ID,
      outcome: 'PASS' as const,
      projectionDigests: [] as string[],
      invariantTotal: 1,
      invariantPassCount: 1,
      invariantNaCount: 0,
      invariantViolationCount: 0,
      findingCount: 0,
    } as unknown as Parameters<typeof validateSemanticEvaluationReceipt>[0];

    // Should not throw.
    validateSemanticEvaluationReceipt(v1Receipt);
  });

  test('v1 ANOMALY receipt without coverage fields validates successfully', () => {
    const v1Receipt = {
      schemaVersion: SEMANTIC_EVALUATION_RECEIPT_VERSION_V1,
      receiptId: 'receipt:sha256:000000000000000000000000',
      oracleId: ORACLE_ID,
      outcome: 'ANOMALY' as const,
      projectionDigests: [] as string[],
      invariantTotal: 1,
      invariantPassCount: 0,
      invariantNaCount: 0,
      invariantViolationCount: 1,
      findingCount: 1,
    } as unknown as Parameters<typeof validateSemanticEvaluationReceipt>[0];

    // Should not throw.
    validateSemanticEvaluationReceipt(v1Receipt);
  });
});

// ===========================================================================
// 12. Deterministic receipt IDs for identical partial evaluations.
// ===========================================================================

test.describe('Phase 11A.1 §12: deterministic receipt IDs', () => {
  test('two identical PARTIAL_COVERAGE receipts produce the same receiptId', () => {
    const input = {
      oracleId: ORACLE_ID,
      outcome: 'PARTIAL_COVERAGE' as const,
      expectationId: 'ripple.common-exchange.read.real-source-collection',
      sourceProvenance: PHASE11_PROVENANCE,
      invariantTotal: 1,
      invariantPassCount: 1,
      invariantNaCount: 0,
      invariantViolationCount: 0,
      findingCount: 0,
      coverageState: 'PARTIAL_COVERAGE_NO_VIOLATION' as const,
      inspectedItemCount: 128,
      violatingItemCount: 0,
      journeyId: JOURNEY_ID,
      stepId: STEP_ID,
    };

    const r1 = buildSemanticEvaluationReceipt(input);
    const r2 = buildSemanticEvaluationReceipt(input);

    expect(r1.receiptId).toBe(r2.receiptId);
    expect(r1.receiptId).toMatch(/^receipt:sha256:[0-9a-f]{24}$/);
  });

  test('PASS and PARTIAL_COVERAGE receipts produce different receiptIds', () => {
    const base = {
      oracleId: ORACLE_ID,
      expectationId: 'ripple.common-exchange.read.real-source-collection',
      sourceProvenance: PHASE11_PROVENANCE,
      invariantTotal: 1,
      invariantPassCount: 1,
      invariantNaCount: 0,
      invariantViolationCount: 0,
      findingCount: 0,
    };

    const passReceipt = buildSemanticEvaluationReceipt({ ...base, outcome: 'PASS' });
    const partialReceipt = buildSemanticEvaluationReceipt({
      ...base,
      outcome: 'PARTIAL_COVERAGE',
      coverageState: 'PARTIAL_COVERAGE_NO_VIOLATION',
      inspectedItemCount: 128,
      violatingItemCount: 0,
    });

    expect(passReceipt.receiptId).not.toBe(partialReceipt.receiptId);
    expect(passReceipt.outcome).toBe('PASS');
    expect(partialReceipt.outcome).toBe('PARTIAL_COVERAGE');
  });
});

// ===========================================================================
// 13. Privacy sentinel sweep — no raw-value / sentinel leakage in receipts.
// ===========================================================================

test.describe('Phase 11A.1 §13: privacy sentinel sweep', () => {
  test('receipt built from partial-coverage evaluation has no sentinel leaks', () => {
    const body = generateExchangeArray(130);
    const expectation = collectionExpectation();
    const result = evaluateCollection(body, expectation);
    expect(result.outcome).toBe('PARTIAL_COVERAGE');

    // Build receipt using the same parameters the hook would derive.
    const receipt = buildSemanticEvaluationReceipt({
      oracleId: ORACLE_ID,
      outcome: 'PARTIAL_COVERAGE',
      expectationId: expectation.expectationId,
      sourceProvenance: expectation.sourceProvenance,
      invariantTotal: 1,
      invariantPassCount: 1,
      invariantNaCount: 0,
      invariantViolationCount: 0,
      findingCount: 0,
      coverageState: 'PARTIAL_COVERAGE_NO_VIOLATION',
      inspectedItemCount: 128,
      violatingItemCount: 0,
    });

    const leaks = sweepForSentinelLeaks(receipt);
    expect(leaks).toHaveLength(0);

    // Verify safe fields only — no raw IDs, no absolute paths.
    const serialized = JSON.stringify(receipt);
    expect(serialized).not.toContain('/home/');
    expect(serialized).not.toContain('/tmp/');
    expect(serialized).not.toContain('SENTINEL');
  });

  test('receipt built from anomaly evaluation has no sentinel leaks', () => {
    const body = Array.from({ length: 5 }, (_, i) => {
      if (i === 2) return { month: SENTINEL.WRONG_TYPE, exchange_rate: { usd: 1.0 } };
      return validExchangeItem(i);
    });
    const expectation = collectionExpectation();
    const result = evaluateCollection(body, expectation);
    expect(result.outcome).toBe('ANOMALY');

    const receipt = buildSemanticEvaluationReceipt({
      oracleId: ORACLE_ID,
      outcome: 'ANOMALY',
      expectationId: expectation.expectationId,
      sourceProvenance: expectation.sourceProvenance,
      projectionDigests: result.findings[0]?.projectionDigests ?? [],
      invariantTotal: 1,
      invariantPassCount: 0,
      invariantNaCount: 0,
      invariantViolationCount: 1,
      findingCount: 1,
      coverageState: 'VIOLATION',
      inspectedItemCount: 5,
      violatingItemCount: 1,
    });

    const leaks = sweepForSentinelLeaks(receipt);
    expect(leaks).toHaveLength(0);
  });

  test('sweep the full evaluation result for sentinel leaks', () => {
    const body = Array.from({ length: 130 }, (_, i) => {
      if (i === 0) return { month: SENTINEL.MONTH, exchange_rate: { usd: 1.0 } };
      if (i === 57) return { month: SENTINEL.WRONG_TYPE, exchange_rate: { usd: 57.0 } };
      if (i === 127) return { month: SENTINEL.NAME, exchange_rate: { usd: 127.0 } };
      return validExchangeItem(i);
    });
    const expectation = collectionExpectation();
    const result = evaluateCollection(body, expectation);

    // Sweep findings and invariant evaluations.
    expect(sweepForSentinelLeaks(result.findings)).toHaveLength(0);
    expect(sweepForSentinelLeaks(result.invariantEvaluations)).toHaveLength(0);
  });
});
