#!/usr/bin/env node

// F-PERF-6 weight table generator (task-local).
//
// Derives a deterministic per-file duration table from the lane timing
// documents written by the Playwright timing reporter, so shard planning can
// balance by measured cost instead of file count. The table is committed data:
// membership stays reproducible on every host, and regenerating it is an
// explicit action.
//
// Usage:
//   node .agent/tasks/nightwatch-test-infrastructure-performance-v1/harness/shard-weights.mjs \
//     [--dir=test-results/timings] [--out=config/shard-weights.v1.json]

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const root = process.cwd();
const flag = (name, fallback) => {
  const argument = process.argv.find((value) => value.startsWith(`--${name}=`));
  return argument === undefined ? fallback : argument.slice(name.length + 3);
};
const documentDirectory = path.resolve(root, flag('dir', 'test-results/timings'));
const outputPath = path.resolve(root, flag('out', 'config/shard-weights.v1.json'));

const samples = new Map();
let documentCount = 0;
let entries;
try {
  entries = fs.readdirSync(documentDirectory, { withFileTypes: true });
} catch {
  console.error(JSON.stringify({ result: 'NO_TIMING_DOCUMENTS', directory: documentDirectory }));
  process.exit(1);
}
for (const entry of entries) {
  if (!entry.isFile() || !entry.name.endsWith('.json')) continue;
  try {
    const document = JSON.parse(fs.readFileSync(path.join(documentDirectory, entry.name), 'utf8'));
    if (document.schemaVersion !== 'nightwatch.playwright-timings.v1' || !Array.isArray(document.files)) continue;
    documentCount += 1;
    for (const file of document.files) {
      if (typeof file.file !== 'string' || !/^(?:tests|scenarios|ui)\//.test(file.file) || file.file.includes('..')) continue;
      const duration = Number(file.durationMs);
      if (!Number.isFinite(duration) || duration < 0) continue;
      const list = samples.get(file.file) ?? [];
      list.push(duration);
      samples.set(file.file, list);
    }
  } catch {
    // An unreadable or forged document contributes nothing.
  }
}
const weights = {};
for (const file of [...samples.keys()].sort()) {
  const list = [...samples.get(file)].sort((left, right) => left - right);
  const middle = Math.floor(list.length / 2);
  const median = list.length % 2 === 0 ? Math.round(((list[middle - 1] ?? 0) + (list[middle] ?? 0)) / 2) : (list[middle] ?? 0);
  // A file that measured 0 ms (for example, a skip-only environment) still
  // costs a worker slot; it is never planned as free.
  weights[file] = Math.max(1, median);
}
const digest = `sha256:${crypto.createHash('sha256').update(JSON.stringify(weights), 'utf8').digest('hex').slice(0, 24)}`;
const table = {
  schemaVersion: 'nightwatch.shard-weights.v1',
  note: 'Per-file maximum measured duration from lane timing documents. Generated by the task harness; used only for deterministic shard balancing, never as a pass/fail authority.',
  documents: documentCount,
  weightDigest: digest,
  weights,
};
fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, `${JSON.stringify(table, null, 2)}\n`, 'utf8');
console.log(JSON.stringify({ result: 'WRITTEN', file: path.relative(root, outputPath), files: Object.keys(weights).length, documents: documentCount, weightDigest: digest }));
